<?php

namespace AppBundle\Repository;

/**
 * AzpisailaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AzpisailaRepository extends \Doctrine\ORM\EntityRepository
{
}
