<?php

/*
 *     Iker Ibarguren <@ikerib>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace AppBundle\Repository;

/**
 * CalendarRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsernameYear($username, $year)
    {
        $em = $this->getEntityManager();

        $dql = /** @lang text */
            '
            SELECT c
            FROM AppBundle:Calendar c
              INNER Join c.user u
            WHERE u.username LIKE :username
              AND c.year = :year
        ';

        $query = $em->createQuery($dql);
        $query->setParameter('username', $username);
        $query->setParameter('year', $year);

        return $query->getResult();
    }

    public function findAllCalendarsByUsername($username)
    {
        $em = $this->getEntityManager();

        $dql = /** @lang text */
            '
            SELECT c
            FROM AppBundle:Calendar c
              INNER Join c.user u
            WHERE u.username LIKE :username
            Order by c.year desc
        ';

        $query = $em->createQuery($dql);
        $query->setParameter('username', $username);

        return $query->getResult();
    }

    public function getEgutegiUrteak()
    {
        $sql = /** @lang text */
            "SELECT DISTINCT(`year`) FROM `calendar`";
        $params = array();

        try {
            return $this->getEntityManager()->getConnection()->executeQuery( $sql, $params )->fetchAll();
        } catch ( DBALException $e ) {
            throw new $e;
        }
    }
}
