<?php

/*
 *     Iker Ibarguren <@ikerib>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace AppBundle\Repository;

/**
 * DocumentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCalendarDocuments($calendarid)
    {
        $em = $this->getEntityManager();

        $dql = '
            SELECT d
            FROM AppBundle:Document d
              INNER Join d.calendar c
            WHERE c.id LIKE :calendarid
        ';

        $query = $em->createQuery($dql);
        $query->setParameter('calendarid', $calendarid);

        return $query->getResult();
    }
}
