<?php

namespace AppBundle\Repository;

/**
 * GutxienekoakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GutxienekoakRepository extends \Doctrine\ORM\EntityRepository
{
}
