<?php

namespace AppBundle\Repository;

/**
 * GutxienekoakdetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GutxienekoakdetRepository extends \Doctrine\ORM\EntityRepository
{
}
