<?php

namespace AppBundle\Repository;

/**
 * KuadranteaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuadranteaRepository extends \Doctrine\ORM\EntityRepository
{
}
