<?php

namespace AppBundle\Repository;

/**
 * LizentziamotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LizentziamotaRepository extends \Doctrine\ORM\EntityRepository
{
}
