<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserUnreadMessages($userid)
    {
        $qb = $this->_em->createQueryBuilder()
                        ->select('m')
                        ->from('AppBundle:Message', 'm')
                        ->innerJoin('m.user', 'u')
                        ->andWhere('u.id=:userid')->setParameter('userid', $userid)
                        ->andwhere('m.readed=0');


        return $qb->getQuery()->getResult();
    }


    public function getAllMessages()
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('m, u')
            ->from('AppBundle:Message', 'm')
            ->innerJoin('m.user', 'u')
            ;

        return $qb->getQuery()->getResult();
    }

    public function findByParameter($q)
    {
        $qb = $this->_em->createQueryBuilder();
        if ($q === 'unread') {
            $qb = $qb->select('m')
                                ->from('AppBundle:Message', 'm')
                                ->where('m.readed=0');
        }

        return $qb->getQuery()->getResult();
    }
}
