<?php

namespace AppBundle\Repository;

/**
 * SailaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SailaRepository extends \Doctrine\ORM\EntityRepository
{
}
