<?php

namespace AppBundle\Repository;

/**
 * SinatzaileakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinatzaileakRepository extends \Doctrine\ORM\EntityRepository
{
}
