app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api:
    resource: "@ApiBundle/Controller/ApiController.php"
    type:     rest
    prefix:   /api/

Messages:
    resource: "@ApiBundle/Controller/MessageController.php"
    type:     rest
    prefix:   /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
