security:
    # Preserve plain text password in token for refresh the user.
    # Analyze the security considerations before turn off this setting.
    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN,ROLE_ADMIN, ROLE_BIDERATZAILE]

    providers:
        chain_provider:
           chain:
              providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
           id: fr3d_ldap.security.user.provider
        fos_userbundle:
           id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            fr3d_ldap:  ~
            security: false
            form_login:
                always_use_default_target_path: true
                default_target_path: /homepage
            logout:       true
            anonymous:    true

        main:
            logout_on_user_change: true
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /mycalendar
            logout:       true
            anonymous:    true
            switch_user:
                provider:   fos_userbundle
                role: ROLE_BIDERATZAILEA

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/kuadrantea, role: [ROLE_ARDURADUNA] }
        - { path: ^/admin/kuadranteaexcel, role: [ROLE_ARDURADUNA] }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_BIDERATZAILEA, ROLE_SUPER_ADMIN] }
